## Numpy Array Operations

In [16]:
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [18]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element:", arr_2D[1,2])
print("Entire row:", arr_2D[1])
print("Enter row: ", arr_2D[:,1])

Specific Element: 6
Entire row: [4 5 6]
Enter row:  [2 5 8]


### Sorting

In [19]:
unsorted = np.array([3,1,5,4,7,9,8,2,1])
print("sorted array: ", np.sort(unsorted))

arr_2D_unsorted = np.array([[3,1],[2,5],[2,1]])
print("Sorted 2D array by column:", np.sort(arr_2D_unsorted, axis=0))
print("Sorted 2D array by row:", np.sort(arr_2D_unsorted, axis=1))

sorted array:  [1 1 2 3 4 5 7 8 9]
Sorted 2D array by column: [[2 1]
 [2 1]
 [3 5]]
Sorted 2D array by row: [[1 3]
 [2 5]
 [1 2]]


### Filter

In [20]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] #In you can write expression in square brackets
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


### Fancy indexing v/s np.where()

In [21]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, "true", "false") #creates an array with specific conditions
print(condition_array) #prints the array with the conditions applied

# above code explaination
"""if (numbers > 5):
    True
else:
    False"""


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [32]:
#combining an array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2 #Not to do, Wrong method
print(combined) #Output: [5 7 9]

combined = np.concatenate((arr1,arr2)) #pass array as tuple to method
print(combined) #Output: [1 2 3 4 5 6]

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility


In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("compatibility shapes", a.shape == b.shape)
print("compatibility shapes", a.shape == c.shape)

compatibility shapes True
compatibility shapes False


### Adding Row and Col to an array

In [41]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print(with_new_row,"\n")


_original = np.array([[7],[8]])
new_col = np.array([[7],[8]])

_with_new_col = np.hstack((_original,new_col))
with_new_col = np.hstack((original,new_col))
print(_with_new_col,"\n")
print(with_new_col)


[[1 2]
 [3 4]
 [5 6]] 

[[7 7]
 [8 8]] 

[[1 2 7]
 [3 4 8]]


### Removing an Element

In [43]:
arr= np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)

print("array after deletion: ", deleted)

array after deletion:  [1 2 4 5 6]
