## Numpy array and basics

In [ ]:
import numpy as np 

In [ ]:

# import numpy as np

arr_1D = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1D)

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:", arr_2D)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List v/s Numpy array

In [3]:
py_list = [1, 2, 3, 4, 5]
print("Python List:", py_list*2)

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Numpy Array:", np_arr*2)

import time
current_time = time.time()
py_list = [i*2 for i in range(1000000)]
print("Time taken for list:", time.time()-current_time)

current_time = time.time()
np_arr = np.arange(1000000)*2
print("Time taken for numpy array:", time.time()-current_time)

Python List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array: [[ 2  4  6]
 [ 8 10 12]]
Time taken for list: 0.043189287185668945
Time taken for numpy array: 0.003526449203491211


### Creating arrays from scratch

In [4]:
zeros = np.zeros((2, 2))
print("Zeros:", zeros)

ones = np.ones((2,2))
print("Ones:", ones)

eye = np.eye(2)
print("Identity Matrix:", eye)

random = np.random.random((2,2))
print("Random Matrix:", random)

sequence = np.arange(0, 10, 2)
print("Sequence:", sequence)

linspace = np.linspace(0, 10, 6)
print("Linspace:", linspace)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Reshape:", arr.reshape(3, 2))




Zeros: [[0. 0.]
 [0. 0.]]
Ones: [[1. 1.]
 [1. 1.]]
Identity Matrix: [[1. 0.]
 [0. 1.]]
Random Matrix: [[0.59187687 0.46566035]
 [0.00911851 0.18727978]]
Sequence: [0 2 4 6 8]
Linspace: [ 0.  2.  4.  6.  8. 10.]
Shape: (2, 3)
Reshape: [[1 2]
 [3 4]
 [5 6]]


### Vector, Matries and Tensors

In [5]:
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Tensor:", tensor)

Vector: [1 2 3 4 5]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Arrays Properties

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Transpose:", arr.T)
print("shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size: ", arr.itemsize)

Transpose: [[1 4]
 [2 5]
 [3 6]]
shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64
Item Size:  8


### Reshaping an arrays

In [7]:
arr = np.arange(12)
print("arr:", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened:", flattened)

# ravel returns a view of the original array, instead of a copy
raveled = reshaped.ravel()
print("Raveled:", raveled)

#transpose
trans = reshaped.T
print("Transpose of reshaped:\n", trans)

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose of reshaped:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
